menu:
    博客: /
    rss: /atom.xml
    xmgeeks: http://xmgeeks.com

favicon: /favicon.png
logo: /favicon.png

# comment
# e.g disqus: seansun
disqus: 
duoshuo: 

# google-analytics:
ga: UA-72012594-1
# baidu-analytics:
ba: //hm.baidu.com/hm.js?df62ae5b2a165cb3e11daca2cc8db6eb
